### PR TITLE
fix: use var instead of let

### LINKED ISSUE #194: let glob in line 7
The use of 'let' is causing my project to fail because is not supporting it yet. Is is necesary to be?
How could I force my npm install to use the previous version (2.6.3)?
imagen

### PR DESCRIPTION
**Pull request by Tidyzq**
fix #194

### CODE REVIEW

**Comment by LinusU** [comment]
@isaacs would appreciate a speedy merge and release of this, the CI pipeline for [form-data](https://github.com/form-data/form-data/pull/435) is currently broken on Node.js 4.x 😅

**Comment by jbustamovej** [comment]
Agreed. This breaks our production systems. Removing support for node4 should be done as a major version upgrade.

**Comment by herman-rogers** [comment]
Yes this also breaks our production build - would love to see this PR go in, otherwise we'll have to pin it to the previous version.

**Comment by lbeschastny** [comment]
@isaacs could you also deprecate `rimraf@2.7.0` to prevent it from being installed?

And thanks for a quick fix, by the way. ;)

**Pull request closed without merging**
