### PR TITLE
add options.disableGlob = true if !glob

### LINKED ISSUE #221: Error: glob dependency not found, set `options.disableGlob = true` if intentional
Upon executing `this.browser.close()` to end a puppeteer process, the aforementioned error occurs every time. 

From what I can tell, `options` is defined as an empty object on line 51 of rimraf.js. Is it possible to add some logic into rimraf to check whether the `try/catch`block on line 5-9 of rimraf.js successfully requires glob?

One solution would be to add the following into the `rimraf` function on line 48:

```
  if(!glob) {
    options.disableGlob = true;
  } 
```

### PR DESCRIPTION
**Pull request by sunil-sandhu**
Fixed #221

### CODE REVIEW

**Comment by dennisjade** [comment]
Hopefully this one will be merge.

**Comment by martinstark** [comment]
Also waiting for this to be merged

**Comment by Osiris-Team** [comment]
Now we are 4 people waiting :/

**Comment by isaacs** [comment]
No longer applicable in v4.

**Pull request closed without merging**
